services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    environment:
      RAILS_ENV: development
    command: bin/rails server -b 0.0.0.0
