---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/examples":
    get:
      summary: Retrieve examples
      tags:
      - Examples
      responses:
        '200':
          description: successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                - message
servers:
- url: http://localhost:3000
