---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/examples":
    get:
      summary: Retrieves examples
      tags:
      - Examples
      responses:
        '200':
          description: examples found
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
